name: Slurm Integration Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  slurm:
    runs-on: ubuntu-18.04
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Checkout TorchX
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-west-2
        continue-on-error: true
      - name: Install Dependencies
        run:
          set -ex

          pip install wheel ec2instanceconnectcli
      - name: Run Slurm Integration Tests
        env:
          SLURM_INSTANCE_MASTER: ${{ secrets.SLURM_INSTANCE_MASTER }}
          SLURM_KNOWN_HOST: ${{ secrets.SLURM_KNOWN_HOST }}
        run: |
          set -e

          mkdir -p ~/.ssh
          echo "$SLURM_KNOWN_HOST" >> ~/.ssh/known_hosts

          scripts/slurmint.sh
